sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t my-app .

script:
  - docker run -e CI=true my-app npm run test -- --coverage --watchAll=false

after_success:
  - docker stop my-app
  - docker rm my-app


